<?php
define('ALM_NOT_FOUND','Lo sentimos, pero el archivo no existe');
define('ALM_KEEP_FILE','Conservar archivo actual');
define('ALM_HOME','Inicio');
define('ALM_LANG_DONE', true);
define('ALM_YES','S&iacute;');
define('ALM_NO','No');
define('ALM_EXPORT_LB','Exportar');
define('ALM_IMPORT_LB','Importar');
define('ALM_EDIT_LB','Editar');
define('ALM_CAN_LB','Cancelar');
define('ALM_SAVE_LB','Guardar');
define('ALM_NEXT_LB','Pr&oacute;ximo');
define('ALM_PREV_LB','Previo');
define('ALM_OPT_LB','Opciones');
define('ALM_MAX','maximizar');
define('ALM_ADD_LB','Agregar');
define('ALM_REC_LB','registros');
define('ALM_DEL_LB','Borrar');
define('ALM_VIEW_LB','Ver');
define('ALM_AL_MSG_DEL','Estas seguro de querer borrar este registro?');
define('ALM_ADMIN_TITLE','Administración');
define('ALM_WCOME','Bienvenido! Conectado como:');
define('ALM_SEARCH_LB','Buscar');
define('ALM_RESET_LB','Limpiar');
define('ALM_NODATA','No hay datos');
define('ALM_NORDATA','No hay datos relacionados');
define('ALM_SHOWALL','Mostrar todo');
define('ALM_USERNAME','Usuario');
define('ALM_PASSWORD','Contrase&ntilde;a');
define('ALM_AUTH_ERROR','Datos de acceso incorrectos');
define('ALM_NO_COOKIE','No hay soporte para sesisiones. Debe habilitar soporte para cookies antes de continuar.');
define('ALM_LOGIN','Entrar');
define('ALM_LOGOUT','Salir');
define('ALM_SETUP','Configurar');
define('ALM_USERS','Usuarios');
define('ALM_ROLES','Roles');
define('ALM_ACCESS','Accesso');
define('ALM_TABLES','Tablas');
define('ALM_FIELDS','Campos');
define('ALM_DETAIL','Detalle');
define('ALM_TITLE_INDEX','Tablero');
define('ALM_CONTENT_LANG','es');
define('ALM_TINY_LANG','es');

# Set locale, for dates
setlocale(LC_TIME, 'es_ES.UTF-8');
