<?php
define('ALM_LANG_DONE', true);
define('ALM_YES','Yes');
define('ALM_NO','No');
define('ALM_EXPORT_LB','Export');
define('ALM_IMPORT_LB','Import');
define('ALM_REC_LB','records');
define('ALM_DEL_LB','Delete');
define('ALM_VIEW_LB','View');
define('ALM_EDIT_LB','Edit');
define('ALM_CAN_LB','Cancel');
define('ALM_SAVE_LB','Save');
define('ALM_NEXT_LB','Next');
define('ALM_PREV_LB','Previous');
define('ALM_OPT_LB','Options');
define('ALM_MAX','maximize');
define('ALM_ADD_LB','Add');
define('ALM_AL_MSG_DEL','Are you sure to want to delete this record?');
define('ALM_ADMIN_TITLE','Management');
define('ALM_WCOME','Welcome! You are connected as:');
define('ALM_SEARCH_LB','Search');
define('ALM_RESET_LB','Clear');
define('ALM_NODATA','No Data');
define('ALM_NORDATA','No Related Data');
define('ALM_SHOWALL','Show All');
define('ALM_USERNAME','Username');
define('ALM_PASSWORD','Password');
define('ALM_PASS_ERROR','Wrong username and/or password');
define('ALM_NO_COOKIE','No session support. You must enable cookies support before continuing.');
define('ALM_LOGIN','Login');
define('ALM_LOGOUT','Logout');
define('ALM_SETUP','Setup');
define('ALM_USERS','Users');
define('ALM_ROLES','Roles');
define('ALM_ACCESS','Access');
define('ALM_TABLES','Tables');
define('ALM_FIELDS','Fields');
define('ALM_DETAIL','Details');
define('ALM_TITLE_INDEX','Dashboard');

# Set locale, for dates
setlocale(LC_TIME, 'en_US.UTF-8');
